/**
 * Defines the supported academic document types.
 *
 * This enum drives:
 * - documentclass selection
 * - base project structure
 * - initial chapters/files
 */
export enum DocumentType {
  ARTICLE = 'article',
  REPORT = 'report',
  BOOK_THESIS = 'book_thesis'
}

/**
 * Defines how LaTeXiS should behave when the target
 * project directory already exists.
 */
export enum CreationMode {
  /**
   * The target directory does not exist.
   * A new project is created from scratch.
   */
  EMPTY = 'empty',

  /**
   * The target directory exists.
   * Only missing files and folders are created.
   * Existing content is never overwritten.
   */
  MERGE = 'merge',

  /**
   * The target directory exists.
   * A new subfolder is created inside it.
   */
  SUBFOLDER = 'subfolder'
}

/**
 * Core model representing an academic LaTeX project
 * to be generated by LaTeXiS.
 *
 * This model is:
 * - Built from user input
 * - Validated before filesystem operations
 * - Passed to the scaffold generator
 */
export interface AcademicProject {
  /**
   * Type of academic document.
   */
  documentType: DocumentType;

  /**
   * Human-readable academic title.
   * Used in LaTeX metadata (e.g. \title{}).
   */
  projectTitle: string;

  /**
   * Normalized directory name for the project.
   * Example: "tesis_de_maestria"
   */
  projectDirectoryName: string;

  /**
   * Absolute base path where the project
   * directory will be created.
   */
  basePath: string;

  /**
   * Strategy to apply if the target directory
   * already exists.
   */
  creationMode: CreationMode;
}